services:
  backend-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GRANIAN_RELOAD=1
      - UV_NO_DEV=0
    networks: [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 2s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .patroni/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

#  ---

  postgres:
    image: postgres:18-alpine
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  #  ---

  etcd1: &etcd
    build:
      context: ./patroni
    networks: [ ledger-network ]
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
      ETCD_UNSUPPORTED_ARCH: arm64
    container_name: demo-etcd1
    hostname: etcd1
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380
    restart: unless-stopped
    profiles: [patroni]

  etcd2:
    <<: *etcd
    container_name: demo-etcd2
    hostname: etcd2
    command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2380
    restart: unless-stopped
    profiles: [patroni]

  etcd3:
    <<: *etcd
    container_name: demo-etcd3
    hostname: etcd3
    command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380
    restart: unless-stopped
    profiles: [patroni]

  haproxy:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: haproxy
    container_name: demo-haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
    command: haproxy
    environment: &haproxy_env
      ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
      PATRONI_SCOPE: demo
    restart: unless-stopped
    profiles: [patroni]

  patroni1:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: patroni1
    container_name: demo-patroni1
    environment:
      <<: *haproxy_env
      PATRONI_NAME: patroni1
    restart: unless-stopped
    volumes:
      - pg_patroni1:/var/lib/postgresql
    profiles: [patroni]

  patroni2:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: patroni2
    container_name: demo-patroni2
    environment:
      <<: *haproxy_env
      PATRONI_NAME: patroni2
    restart: unless-stopped
    volumes:
      - pg_patroni2:/var/lib/postgresql
    profiles: [patroni]


networks:
    ledger-network:
      driver: bridge

volumes:
  pg_patroni1:
  pg_patroni2:
  postgres_data:
