x-common-env-map: &common-env-map
  POSTGRES_USER_FILE: /run/secrets/pg_user
  POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass
  POSTGRES_DB_FILE: /run/secrets/pg_db

services:
  backend-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      <<: *common-env-map
      GRANIAN_RELOAD: 1
      UV_NO_DEV: 1
#      - GRANIAN_RELOAD=1
#      - UV_NO_DEV=0
#      - POSTGRES_USER_FILE=/run/secrets/pg_user
#      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_pass
#      - POSTGRES_DB_FILE=/run/secrets/pg_db
#      - *common-env-map
    secrets:
      - pg_user
      - pg_pass
      - pg_db
    networks: [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 2s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .patroni/
            - .secrets
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile

#  ---

  postgres:
    image: postgres:18
    container_name: my_postgres
    restart: unless-stopped
    command: [
      "postgres",
      "-c", "shared_buffers=8GB",
      "-c", "effective_cache_size=24GB",
      "-c", "work_mem=64MB",
      "-c", "maintenance_work_mem=2GB",
      "-c", "wal_buffers=64MB",
      "-c", "huge_pages=try",
      "-c", "max_connections=200",
      "-c", "superuser_reserved_connections=3",
      "-c", "wal_level=replica",
      "-c", "max_wal_size=4GB",
      "-c", "min_wal_size=1GB",
      "-c", "wal_compression=on",
      "-c", "synchronous_commit=on",
      "-c", "checkpoint_timeout=15min",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "bgwriter_delay=200ms",
      "-c", "bgwriter_lru_maxpages=100",
      "-c", "bgwriter_lru_multiplier=2.0",
      "-c", "random_page_cost=1.1",
      "-c", "effective_io_concurrency=200",
      "-c", "default_statistics_target=100",
      "-c", "max_parallel_workers_per_gather=2",
      "-c", "max_parallel_workers=8",
      "-c", "max_parallel_maintenance_workers=2",
      "-c", "autovacuum=on",
      "-c", "autovacuum_max_workers=3",
      "-c", "autovacuum_vacuum_scale_factor=0.1",
      "-c", "autovacuum_analyze_scale_factor=0.05",
      "-c", "autovacuum_vacuum_cost_delay=2ms",
      "-c", "autovacuum_vacuum_cost_limit=1000",
      "-c", "log_filename='postgresql-%Y-%m-%d.log'",
      "-c", "log_min_duration_statement=1000",
      "-c", "log_checkpoints=on",
      "-c", "log_lock_waits=on",
      "-c", "log_temp_files=0",
      "-c", "log_autovacuum_min_duration=0",
      "-c", "log_line_prefix='%m [%p] %q%u@%d '",
      "-c", "password_encryption=scram-sha-256"
    ]
    environment: *common-env-map
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 120s
    secrets:
      - pg_user
      - pg_pass
      - pg_db

  #  ---

  etcd1: &etcd
    build:
      context: ./patroni
    networks: [ ledger-network ]
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
      ETCD_UNSUPPORTED_ARCH: arm64
    container_name: demo-etcd1
    hostname: etcd1
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380
    restart: unless-stopped
    profiles: [patroni]

  etcd2:
    <<: *etcd
    container_name: demo-etcd2
    hostname: etcd2
    command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2380
    restart: unless-stopped
    profiles: [patroni]

  etcd3:
    <<: *etcd
    container_name: demo-etcd3
    hostname: etcd3
    command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380
    restart: unless-stopped
    profiles: [patroni]

  haproxy:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: haproxy
    container_name: demo-haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
    command: haproxy
    environment: &haproxy_env
      ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
      PATRONI_SCOPE: demo
    restart: unless-stopped
    profiles: [patroni]

  patroni1:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: patroni1
    container_name: demo-patroni1
    environment:
      <<: *haproxy_env
      PATRONI_NAME: patroni1
    restart: unless-stopped
    volumes:
      - pg_patroni1:/var/lib/postgresql
    profiles: [patroni]

  patroni2:
    build:
      context: ./patroni
    networks: [ ledger-network ]
    env_file: patroni/docker/patroni.env
    hostname: patroni2
    container_name: demo-patroni2
    environment:
      <<: *haproxy_env
      PATRONI_NAME: patroni2
    restart: unless-stopped
    volumes:
      - pg_patroni2:/var/lib/postgresql
    profiles: [patroni]


networks:
    ledger-network:
      driver: bridge

volumes:
  pg_patroni1:
  pg_patroni2:
  postgres_data:

secrets:
#  pg_pass:
#    file: secrets/postgres/pgpass.conf
  pg_user:
    file: secrets/postgres/pg_user.txt
  pg_pass:
    file: secrets/postgres/pg_pass.txt
  pg_db:
    file: secrets/postgres/pg_db.txt