[project]
name = "ledger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "granian[reload,uvloop]>=2.7.1",
    "litestar>=2.20.0",
]

[dependency-groups]
dev = [
    "ipython>=9.10.0",
]
